name = "example"
description = "Shiny new project"
version = "0.0.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

executables = ["example"]

[[depends-on]]
chests = "~0.1.1"

[[pins]]
chests = { path='../' }
