name = "chests"
description = "Chests are bounded containers"
version = "0.1.1"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

licenses = "BSD-3-Clause"
website = "https://github.com/JeremyGrosser/chests"
tags = ["containers", "bounded", "nostd", "embedded"]
